[package]
name = "riscv"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.*"
num-derive = "0.*"
num-traits = { version = "0", default-features = false }

[features]
dbg = []
mch = []
spv = []
hpv = []
virt = []
user = []
trap = []